services:
  - type: web
    name: huggingface-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 180 --workers 2
    envVars:
      - key: HF_API_KEY
        sync: false
      - key: PORT
        value: 10000
```

## 🚀 Step 6: Deploy on Render

1. Go to [Render Dashboard](https://dashboard.render.com/)
2. Click **"New +"** → **"Web Service"**
3. Connect your GitHub repo
4. Render will detect the files automatically
5. **IMPORTANT**: Add your Hugging Face API key:
   - Click **"Add Environment Variable"**
   - Key: `HF_API_KEY`
   - Value: Paste your token from Step 1
6. Click **"Create Web Service"**
7. Wait 3-5 minutes for deployment

## ✅ Step 7: Test It Works

Once deployed, visit:
```
https://your-new-app-name.onrender.com/test-hf
